[admiral]
items = ["ls", "loop", "foo", "baz", "bar"]

[foo]
path = "foo.sh"
reload = 1

[bar]
path = "bar.sh"
reload = 5

[ls]
path = ["/usr/bin/ls", "--version"]

[loop]
path = "loop.sh"

[unused]
path = "unused.sh"
reload = 60
