[admiral]
items = ["left", "workspaces",
         "center", "title",
         "right", "clock"]

[workspaces]
path = "workspaces.sh"

[title]
path = ["/usr/bin/xtitle", "-s", "-t", "100"]

[clock]
path = ["/usr/bin/date", "+%-I:%M %p  "]
reload = 1

# Used for formatting lemonbar
[left]
path = ["/usr/bin/echo", "%{l}"]

[center]
path = ["/usr/bin/echo", "%{c}"]

[right]
path = ["/usr/bin/echo", "%{r}"]
